name = "jiaoshi"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "classroom_db"
database_id = "543aeb14-bef2-4570-a97a-d08489032d72"
